version: '2'
services:
  php:
    image: my-php
    volumes:
      - ./:/app
    working_dir: /app
  web:
    image: my-nginx
    volumes:
      - ./:/app
    depends_on:
      - php
    ports:
      - 83:80
  mysql:
    image: mysql:5.7.21
    volumes:
      - ./:/app
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=world
      - MYSQL_ROOT_PASSWORD=12345
    working_dir: /app
volumes:
  dbdata:
